# This file is used for building and pushing images
services:
  batcher:
    build:
      context: .
      dockerfile: disperser/batcher.Dockerfile
    image: ghcr.io/layr-labs/eigenda/batcher:${BUILD_TAG:-latest}
  disperser:
    build:
      context: .
      dockerfile: disperser/disperser.Dockerfile
    image: ghcr.io/layr-labs/eigenda/disperser:${BUILD_TAG:-latest}
  encoder:
    build:
      context: .
      dockerfile: disperser/encoder.Dockerfile
    image: ghcr.io/layr-labs/eigenda/encoder:${BUILD_TAG:-latest}
  retriever:
    build:
      context: .
      dockerfile: retriever/Dockerfile
    image: ghcr.io/layr-labs/eigenda/retriever:${BUILD_TAG:-latest}
  node:
    build:
      context: .
      dockerfile: node/cmd/Dockerfile
    image: ghcr.io/layr-labs/eigenda/node:${BUILD_TAG:-latest}
  churner:
    build:
      context: .
      dockerfile: churner/Dockerfile
    image: ghcr.io/layr-labs/eigenda/churner:${BUILD_TAG:-latest}
  nodeplugin:
    build:
      context: .
      dockerfile: node/plugin/Dockerfile
    image: ghcr.io/layr-labs/eigenda/nodeplugin:${BUILD_TAG:-latest}
