name: "🐞 Bug Report"
title: "[Bug]: <Title>"
description: Something with EigenDA is not working as expected
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the problem!
        Please make sure what you are reporting is a bug with environment and reproducible steps.

  - type: textarea
    attributes:
      label: What happened + What you expected to happen
      description: Describe 1. the bug 2. expected behavior 3. useful information (e.g., logs)
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened. Further,
        please also explain why you think the behaviour is erroneous.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions / Dependencies
      description: Please specify the versions of EigenDA, golang, OS and context of your machine.
      placeholder: >
        Please specify the versions and dependencies.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        Please provide steps or code snippet to reproduce the issue.
      placeholder: >
        Please provide steps or a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Issue Severity
      description: |
        How does this issue affect your experience?
      multiple: false
      options:
          - "Low: It annoys or frustrates me."
          - "Medium: It is a significant difficulty but I can work around it."
          - "High: It blocks me from completing my task."
    validations:
        required: false
